title: pyauthenticator
author: Jan Janssen

execute:
  execute_notebooks           : off

repository:
  url                       : https://github.com/jan-janssen/pyauthenticator
html:
  use_repository_button: true

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org
